/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface RippleEffect {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRippleEffectElement extends Components.RippleEffect, HTMLStencilElement {
    }
    var HTMLRippleEffectElement: {
        prototype: HTMLRippleEffectElement;
        new (): HTMLRippleEffectElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ripple-effect": HTMLRippleEffectElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface RippleEffect {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ripple-effect": RippleEffect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ripple-effect": LocalJSX.RippleEffect & JSXBase.HTMLAttributes<HTMLRippleEffectElement>;
        }
    }
}
